[[manager.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-preview"
desc = "Hide or show preview"

[[manager.prepend_keymap]]
on = [ "m" ]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[manager.prepend_keymap]]
on = [ "'" ]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[manager.prepend_keymap]]
on = [ "b", "d" ]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[manager.prepend_keymap]]
on = [ "b", "D" ]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"

[[manager.prepend_keymap]]
on = "<S-Enter>"
run = "plugin open-with-cmd" 
desc = "Open with command"

[[manager.prepend_keymap]]
on = "i"
run = "plugin easyjump --sync --args=keep"
desc = "Keyjump"

[[manager.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[manager.prepend_keymap]]
on = [ "g", "l" ]
run = 'shell -- ya emit reveal "$(readlink -f "$0")"'
desc = "Follow hovered symlink"
